### ISSUE TITLE
Messed up axes in code.

### ISSUE THREAD

**Issue by hjaremko** [hjaremko/arkanoid#8]
Oops.

**Comment by hjaremko** [comment]
Nevermind...

**Comment by mdymek** [comment]
Brawo!!!

26 wrz 2018 18:29 "Hubert Jaremko" <notifications@github.com> napisał(a):

Closed #8 <https://github.com/hjaremko/arkanoid/issues/8>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hjaremko/arkanoid/issues/8#event-1868910232>, or mute
the thread
